## Logistic Regression

You should build a machine learning pipeline using a logistic regression model. In particular, you should do the following:



*   Load the mnist dataset using Pandas. You can find this dataset in the datasets folder.
*   Split the dataset into training and test sets using Scikit-Learn.
*   Conduct data exploration, data preprocessing, and feature engineering if necessary.
*   Train and test a logistic regression model using Scikit-Learn.
*   Check the documentation to identify the most important hyperparameters, attributes, and methods of the model. Use them in practice.

## Importing libraries

In [171]:
import pandas as pd

## Data Collection

In [192]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

## Load the MNIST Dataset

In [173]:
df = pd.read_csv ("https://raw.githubusercontent.com/m-mahdavi/teaching/refs/heads/main/datasets/mnist.csv")
df.head()

,id,class,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,31953,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,34452,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,60897,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,36953,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1981,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Data Exploration
Inspect the full dataset (EDA)

In [174]:
df.shape     # Shape of dataset
df.info() # Column names & data types
df.describe() # Summary statistics
df.columns   # Check Column Names

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Columns: 786 entries, id to pixel784
dtypes: int64(786)
memory usage: 24.0 MB

Index(['id', 'class', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779', 'pixel780',
       'pixel781', 'pixel782', 'pixel783', 'pixel784'],
      dtype='object', length=786)

In [175]:
df.isnull().sum().any()    # Check missing values

np.False_

In [176]:
df.columns

# class: this is the label (0–9)
# pixel1: pixel784 → features

Index(['id', 'class', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779', 'pixel780',
       'pixel781', 'pixel782', 'pixel783', 'pixel784'],
      dtype='object', length=786)

In [177]:
df['class'].value_counts() # Distribution of class

class
1    486
7    426
3    417
8    416
6    391
2    390
0    376
4    369
9    366
5    363
Name: count, dtype: int64

## Separate Features (x) and Target (y)

Separating the features and target so that the model learns to predict the output (class) only from the input data (pixel values), avoiding data leakage and enabling correct supervised learning.

*   X contains pixel features
*   y contains digit labels

In [178]:
X = df.drop('class', axis=1)
y = df['class']

## Train–Test Split

To evaluate the model on unseen data, avoid overfitting, ensure reproducibility, and using stratification maintain balanced class distribution across training and testing sets.

*   80% data is used for training,
*   20% for testing

> stratify=y ensures all digit classes are equally represented

In [179]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y          # Ensures each digit class is proportionally represented.
)

## Data Preprocessing

Logistic Regression requires scaling

StandardScaler to normalize pixel values so all features have equal importance, improve gradient descent convergence, speed up training, and prevent distance-based bias, while avoiding data leakage by fitting only on training data.


*   StandardScaler → best for Gaussian-like data & gradient-based models
*   MNIST pixels after scaling work very well with it

*   Pixel values are standardized
*   Improves convergence and model performance

In [180]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Build & Train Logistic Regression Model



*   Logistic Regression is used for multiclass classification
*   max_iter=1000 ensures convergence
*   lbfgs solver is suitable for large datasets

In [181]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

## Test the Model

The trained model predicts digit classes for unseen test data.

In [193]:
y_pred = pipeline.predict(X_test)

## Model Evaluation

In [183]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.88625

In [184]:
## Classification Report
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred, zero_division=0))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96        75
           1       0.91      0.96      0.93        97
           2       0.90      0.92      0.91        78
           3       0.86      0.86      0.86        84
           4       0.85      0.91      0.88        74
           5       0.82      0.77      0.79        73
           6       0.91      0.90      0.90        78
           7       0.91      0.92      0.91        85
           8       0.88      0.80      0.84        83
           9       0.86      0.85      0.86        73

    accuracy                           0.89       800
   macro avg       0.88      0.88      0.88       800
weighted avg       0.89      0.89      0.89       800

In [185]:
## Confusion Matrix # These metrics evaluate how well the model classifies handwritten digits
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[73,  0,  0,  1,  0,  1,  0,  0,  0,  0],
       [ 0, 93,  0,  2,  0,  0,  0,  0,  2,  0],
       [ 1,  0, 72,  0,  3,  0,  1,  0,  1,  0],
       [ 0,  0,  1, 72,  0,  4,  1,  3,  3,  0],
       [ 0,  1,  0,  1, 67,  1,  1,  0,  0,  3],
       [ 2,  3,  1,  4,  0, 56,  1,  2,  3,  1],
       [ 0,  0,  2,  0,  2,  2, 70,  1,  0,  1],
       [ 0,  1,  1,  1,  1,  0,  0, 78,  0,  3],
       [ 0,  3,  3,  2,  2,  2,  3,  0, 66,  2],
       [ 1,  1,  0,  1,  4,  2,  0,  2,  0, 62]])

## Important Hyperparameters, Attributes & Methods

### Model Attributes

In [186]:
log_reg.coef_
log_reg.intercept_
log_reg.classes_
log_reg.n_iter_

array([69], dtype=int32)

### Important Methods

In [194]:
pipeline.fit(X_train, y_train)
pipeline.predict(X_test)
pipeline.score(X_test, y_test)

0.88625

The model achieved an accuracy of 86.25%, indicating good performance in correctly classifying the test data.

## Build a Proper Machine Learning Pipeline

The pipeline ensures preprocessing and modeling are applied consistently and avoids data leakage.

In [195]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('logistic_regression', LogisticRegression(max_iter=1000))
])

pipeline.fit(X_train, y_train)
pipeline.score(X_test, y_test)

0.88625

Final Conclusion:

In this task, the MNIST dataset was loaded and explored using Pandas. The dataset was split into training and test sets using Scikit-Learn. Feature scaling was applied to normalize pixel values. A Logistic Regression model was trained and evaluated using accuracy, confusion matrix, and classification metrics. Important hyperparameters, attributes, and methods of the model were analyzed, and a complete machine learning pipeline was implemented.