## Logistic Regression

You should build a machine learning pipeline using a logistic regression model. In particular, you should do the following:

*   Load the mnist dataset using Pandas. You can find this dataset in the datasets folder.
*   Split the dataset into training and test sets using Scikit-Learn.
*   Conduct data exploration, data preprocessing, and feature engineering if necessary.
*   Train and test a logistic regression model using Scikit-Learn.
*   Check the documentation to identify the most important hyperparameters, attributes, and methods of the model. Use them in practice.

## Business Problem Understanding

Make a machine learning model that can figure out the digits from the class column in the MNIST database and check its performance with the help of confusion matrix.

## Data Collection

In [ ]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

## Load the MNIST Dataset

In [ ]:
df = pd.read_csv ("https://raw.githubusercontent.com/m-mahdavi/teaching/refs/heads/main/datasets/mnist.csv")
df.head()

,id,class,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,31953,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,34452,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,60897,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,36953,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1981,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Data Exploration
Inspect the full dataset (EDA)

In [ ]:
df.shape     # Shape of dataset

(4000, 786)

In [ ]:
df.info() # Column names & data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Columns: 786 entries, id to pixel784
dtypes: int64(786)
memory usage: 24.0 MB

In [ ]:
df.describe() # Summary statistics

,id,class,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
count,4000.000000,4000.000000,4000.0,4000.0,4000.0,4000.0,4000.0,4000.0,4000.0,4000.0,...,4000.000000,4000.000000,4000.000000,4000.000000,4000.0,4000.0,4000.0,4000.0,4000.0,4000.0
mean,34415.179250,4.439500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.076750,0.015250,0.013000,0.001500,0.0,0.0,0.0,0.0,0.0,0.0
std,20508.890104,2.879655,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.616022,0.964495,0.822192,0.094868,0.0,0.0,0.0,0.0,0.0,0.0
min,17.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25%,16575.750000,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
50%,34435.500000,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
75%,52111.500000,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
max,69998.000000,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,125.000000,61.000000,52.000000,6.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.columns   # Check Column Names

Index(['id', 'class', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779', 'pixel780',
       'pixel781', 'pixel782', 'pixel783', 'pixel784'],
      dtype='object', length=786)

In [ ]:
df.isna().sum() #no missing values found

id          0
class       0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel780    0
pixel781    0
pixel782    0
pixel783    0
pixel784    0
Length: 786, dtype: int64

In [ ]:
df.columns

# class: this is the label (0–9)
# pixel1: pixel784 → features

Index(['id', 'class', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779', 'pixel780',
       'pixel781', 'pixel782', 'pixel783', 'pixel784'],
      dtype='object', length=786)

In [ ]:
df['class'].value_counts() # Distribution of class (Detects class imbalance)

class
1    486
7    426
3    417
8    416
6    391
2    390
0    376
4    369
9    366
5    363
Name: count, dtype: int64

## Separate Features (x) and Target (y)

Separating the features and target so that the model learns to predict the output (class) only from the input data (pixel values), avoiding data leakage and enabling correct supervised learning.


> Prevents data leakage



*   X contains pixel features
*   y contains digit labels (0–9)

In [ ]:
X = df.drop(['id', 'class'], axis=1)  # drop from FEATURES
y = df['class']                       # keep as TARGET

# The id column is non-predictive and is removed, while class is separated as the target to prevent data leakage.

## Train–Test Split

To evaluate the model on unseen data, avoid overfitting, ensure reproducibility, and using stratification maintain balanced class distribution across training and testing sets.

*   80% data is used for training,
*   20% for testing

> stratify=y ensures that all digit classes are equally represented in both the training and testing sets

In [ ]:
df_train, df_test = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df['class'] #stratify is used to make sure all classes have similar proportion of data both in training and in test.
)

In [ ]:
print('df size:', df.shape)
print('df_train size:', df_train.shape)
print('df_test size:', df_test.shape)

df size: (4000, 786)
df_train size: (3200, 786)
df_test size: (800, 786)

## Data Preprocessing - Feature Scaling

Logistic Regression requires scaling

StandardScaler to normalize pixel values so all features have equal importance, improve gradient descent convergence, speed up training, and prevent distance-based bias, while avoiding data leakage by fitting only on training data.


*   StandardScaler → best for Gaussian-like data & gradient-based models
*   MNIST pixels after scaling work very well with it

*   Pixel values are standardized
*   Improves convergence and model performance

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() #Initialize the scaler
X_train_scaled = scaler.fit_transform(X_train)  #Fit only on training data to avoid data leakage
X_test_scaled = scaler.transform(X_test) #Apply the same transformation to test data

## Model Training



*   Logistic Regression is used for multiclass classification
*   max_iter=1000 ensures convergence
*   lbfgs solver is suitable for large datasets

In [ ]:
from sklearn.linear_model import LogisticRegression

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
print('Number of classes:', len(model.classes_))
print('Classes:', model.classes_)

# Double-checking the number of classes after preprocessing (can also be verified during EDA)

Number of classes: 10
Classes: [0 1 2 3 4 5 6 7 8 9]

## Model Evaluation

In [ ]:
train_accuracy = model.score(X_train_scaled, y_train)
print('Training Accuracy:', train_accuracy)

Training Accuracy: 1.0

In [ ]:
test_accuracy = model.score(X_test_scaled, y_test)
print('Test Accuracy:', test_accuracy)

Test Accuracy: 0.88625

In [ ]:
## Confusion Matrix # These metrics evaluate how well the model classifies handwritten digits
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predicted)

array([[73,  0,  0,  1,  0,  1,  0,  0,  0,  0],
       [ 0, 93,  0,  2,  0,  0,  0,  0,  2,  0],
       [ 1,  0, 72,  0,  3,  0,  1,  0,  1,  0],
       [ 0,  0,  1, 72,  0,  4,  1,  3,  3,  0],
       [ 0,  1,  0,  1, 67,  1,  1,  0,  0,  3],
       [ 2,  3,  1,  4,  0, 56,  1,  2,  3,  1],
       [ 0,  0,  2,  0,  2,  2, 70,  1,  0,  1],
       [ 0,  0,  2,  1,  1,  0,  0, 78,  0,  3],
       [ 0,  3,  3,  2,  1,  3,  3,  0, 66,  2],
       [ 1,  1,  0,  1,  5,  2,  0,  1,  0, 62]])

In [ ]:
## Classification Report - evaluates the model’s performance using precision, recall, and F1-score for each digit class.
from sklearn.metrics import classification_report

print(classification_report(y_test, y_predicted, zero_division=0))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96        75
           1       0.92      0.96      0.94        97
           2       0.89      0.92      0.91        78
           3       0.86      0.86      0.86        84
           4       0.85      0.91      0.88        74
           5       0.81      0.77      0.79        73
           6       0.91      0.90      0.90        78
           7       0.92      0.92      0.92        85
           8       0.88      0.80      0.84        83
           9       0.86      0.85      0.86        73

    accuracy                           0.89       800
   macro avg       0.88      0.88      0.88       800
weighted avg       0.89      0.89      0.89       800

Final Conclusion:

In this task, the MNIST dataset was loaded and explored using Pandas. The data was split into training and testing sets using Scikit-Learn. Feature scaling was applied to standardize pixel values. A Logistic Regression model was trained for digit classification and evaluated using accuracy, confusion matrix, and classification metrics.